server:
  port: 8081
spring:
  application:
    name: web
  datasource:
    url: jdbc:mysql://1.1.1.88:3306/liux_pro
    username: root
    password: root
  redis:
    #    host: 192.168.200.128
    host: 1.1.1.88
    port: 6379
    database: 0
    timeout: 1800000
    password:
    lettuce:
      pool:
        max-active: 20 #最大连接数
        max-wait: -1    #最大阻塞等待时间(负数表示没限制)
        max-idle: 5    #最大空闲
        min-idle: 0     #最小空闲
liux-pro:
  host: liux.pro
  id-worker:
    datacenter-id: 1
    sequence: 1
    worker-id: 1
  oss:
    access-key: legend
    secret-key: 123456789
    service: s3
    region: us-east-1
    endpoint: 1.1.1.88:9000
    bucket: liux-pro
    cdn-host: 1.1.1.88:9000/liux-pro
    protocol: http
mybatis:
  configuration:
    map-underscore-to-camel-case: on