server:
  port: 8081
spring:
  application:
    name: web
  redis:
#    host: 192.168.200.128
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 1800000
    password:
    lettuce:
      pool:
        max-active: 20 #最大连接数
        max-wait: -1    #最大阻塞等待时间(负数表示没限制)
        max-idle: 5    #最大空闲
        min-idle: 0     #最小空闲
oss:
  s3:
    access-key: -fLbx3jNQ3roeETUBxGstydVAmoPHqz1vHMXKgfB
    secret-key: -fLbx3jNQ3roeETUBxGstydVAmoPHqz1vHMXKg
    service: s3
    region: mytegion